# Generated by Django 6.0 on 2026-02-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kteb',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover/'),
        ),
    ]
