# Generated by Django 6.0 on 2026-02-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keb', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='توصیه_میکنی_یا_نه',
            field=models.BooleanField(default=True),
        ),
    ]
